---
- name: Enforce SSH key authentication on Ubuntu EC2
  hosts: webservers
  become: true

  tasks:
    - name: Ensure PasswordAuthentication is disabled
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
        backup: yes

    - name: Ensure PubkeyAuthentication is enabled
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PubkeyAuthentication'
        line: 'PubkeyAuthentication yes'
        state: present
        backup: yes

    - name: Ensure root login is disabled 
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present
        backup: yes

    - name: Restart SSH service to apply changes
      ansible.builtin.service:
        name: ssh
        state: restarted

 # --- Fail2Ban Setup ---
    - name: Install Fail2Ban
      ansible.builtin.apt:
        name: fail2ban
        state: present
        update_cache: yes

    - name: Ensure Fail2Ban service is enabled and started
      ansible.builtin.service:
        name: fail2ban
        state: started
        enabled: yes

    - name: Configure Fail2Ban for SSH protection
      ansible.builtin.copy:
        dest: /etc/fail2ban/jail.local
        content: |
          [sshd]
          enabled = true
          port    = ssh
          filter  = sshd
          logpath = /var/log/auth.log
          maxretry = 5
          bantime = 3600
      notify: Restart fail2ban

  handlers:
    - name: Restart fail2ban
      ansible.builtin.service:
        name: fail2ban
        state: restarted